# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /home/winter/mongodb/data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8089:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: examplepassword
#      ME_CONFIG_MONGODB_URL: mongodb://root:examplepassword@mongo:27017/
